### ISSUE TITLE
Out of Memory issue 

### ISSUE THREAD

**Issue by sl-maelledelay** [NAXAM/shimmer-android-binding#1]
Hi, I have this bug when using your shimmer-android-binding.

java.lang.OutOfMemoryError: Failed to allocate a 8472972 byte allocation with 5695120 free bytes and 5MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:975)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
	at com.facebook.shimmer.ShimmerFrameLayout.createBitmapAndGcIfNecessary(ShimmerFrameLayout.java:946)
	at com.facebook.shimmer.ShimmerFrameLayout.getMaskBitmap(ShimmerFrameLayout.java:822)
	at com.facebook.shimmer.ShimmerFrameLayout.drawMasked(ShimmerFrameLayout.java:771)
	at com.facebook.shimmer.ShimmerFrameLayout.dispatchDrawUsingBitmap(ShimmerFrameLayout.java:720)
	at com.facebook.shimmer.ShimmerFrameLayout.dispatchDraw(ShimmerFrameLayout.java:697)
	at android.view.View.draw(View.java:17472)
	at android.view.View.updateDisplayListIfDirty(View.java:16464)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
	at android.view.View.draw(View.java:17472)
	at android.view.View.updateDisplayListIfDirty(View.java:16464)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
	at android.view.View.updateDisplayListIfDirty(View.java:16459)
	at android.view.View.draw(View.java:17238)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3921)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3711)
	at android.view.View.draw(View.java:17472)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:3205)
	at android.view.View.updateDisplayListIfDirty(View.java:16464)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3140)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2939)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7403)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

The bug is fixed in the shimmer-android but this wrapper is based on the previous version.
https://github.com/facebook/shimmer-android/commit/544c5687cc0f1b2e976cd43e806a5f82e81d6462

Do you intend to upgrade your binding?

Thanks

**Comment by petro2050** [comment]
@tuyen-vuduc any update on this?
